<RootWidget>:
    width: 1024.0
    height: 600.0
    TabbedPanel:
        height: 10.0
        width: 60.0
        valign: 'middle'
        do_default_tab: False
        
        TabbedPanelItem:
            text: 'Item 1'
            BoxLayout:
        
        TabbedPanelItem:
            text: 'Item 2'
            BoxLayout:
        
        TabbedPanelItem:
            text: 'Item 3'
            BoxLayout:

    ToggleButton:
        text: 'Toggle Button'
    Button:
        text: 'Button'
    Slider:
    CheckBox:
        active: True